// Generates supabase/migrations/0002_seed.sql from the demo seed data
// in src/. Run: node scripts/generate-seed.mjs
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { seedData } from '../src/utils/storage.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(__dirname, '../supabase/migrations/0002_seed.sql');

const q = (sqlStr) => `'${String(sqlStr).replace(/'/g, "''")}'`;

const listTables = [
  'products',
  'categories',
  'coupons',
  'reviews',
  'blogs',
  'banners',
  'faqs',
  'customers',
  'messages',
  'subscribers'
];

const parts = [];

parts.push(`-- =============================================================
-- Mashroom-Demo — seed data (auto-generated by scripts/generate-seed.mjs)
-- Source of truth: src/data/*.js + seedData in src/utils/storage.js
-- Do not edit by hand — rerun the generator instead.
-- =============================================================`);

for (const table of listTables) {
  const items = seedData[table];
  if (!Array.isArray(items)) throw new Error(`seedData.${table} missing`);
  const ids = new Set();
  for (const item of items) {
    if (!item.id) throw new Error(`seedData.${table} has item without id: ${JSON.stringify(item).slice(0, 80)}`);
    if (ids.has(item.id)) throw new Error(`seedData.${table} duplicate id ${item.id}`);
    ids.add(item.id);
  }
  const json = JSON.stringify(items, null, 2);
  parts.push(`
insert into public.${table} (id, data)
select e.value ->> 'id', e.value
from jsonb_array_elements(${q(json)}::jsonb) as e(value)
on conflict (id) do update set data = excluded.data;`);
}

const settings = {
  site_config: seedData.site_config,
  shipping_tax: seedData.shipping_tax
};
parts.push(`
insert into public.settings (key, data)
select e.key, e.value
from jsonb_each(${q(JSON.stringify(settings, null, 2))}::jsonb) as e(key, value)
on conflict (key) do update set data = excluded.data, updated_at = now();`);

const orders = seedData.orders;
parts.push(`
insert into public.orders (id, user_id, customer_email, status, total, date, data)
select
  o.value ->> 'id',
  null,
  o.value -> 'customer' ->> 'email',
  coalesce(o.value ->> 'status', 'Placed'),
  coalesce((o.value ->> 'total')::numeric, 0),
  (o.value ->> 'date')::timestamptz,
  o.value
from jsonb_array_elements(${q(JSON.stringify(orders, null, 2))}::jsonb) as o(value)
on conflict (id) do update set
  status = excluded.status,
  total = excluded.total,
  date = excluded.date,
  customer_email = excluded.customer_email,
  data = excluded.data;`);

const payload = {
  products: seedData.products,
  categories: seedData.categories,
  coupons: seedData.coupons,
  reviews: seedData.reviews,
  blogs: seedData.blogs,
  banners: seedData.banners,
  faqs: seedData.faqs,
  customers: seedData.customers,
  messages: seedData.messages,
  subscribers: seedData.subscribers,
  orders: seedData.orders,
  settings
};
parts.push(`
-- Payload used by the admin "Reset Demo Data" RPC
insert into public.seed_payload (key, data)
values ('initial', ${q(JSON.stringify(payload, null, 2))}::jsonb)
on conflict (key) do update set data = excluded.data;`);

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, parts.join('\n') + '\n', 'utf8');
console.log(`Wrote ${outPath}`);
