-- =============================================================
-- Mashroom-Demo — seed data (auto-generated by scripts/generate-seed.mjs)
-- Source of truth: src/data/*.js + seedData in src/utils/storage.js
-- Do not edit by hand — rerun the generator instead.
-- =============================================================

insert into public.products (id, data)
select e.value ->> 'id', e.value
from jsonb_array_elements('[
  {
    "id": "prod-101",
    "slug": "fresh-oyster-mushrooms",
    "name": "Fresh Oyster Mushrooms",
    "category": "Fresh Mushrooms",
    "categorySlug": "fresh-mushrooms",
    "price": 149,
    "compareAtPrice": 179,
    "stock": 30,
    "sku": "FR-OY-500",
    "rating": 4.8,
    "reviewCount": 26,
    "shortDescription": "Fresh oyster mushrooms for everyday cooking and food preparation.",
    "longDescription": "Fresh oyster mushrooms from our farm in Pedagadi, Udala, Mayurbhanj, Odisha. A versatile ingredient for homes, restaurants, and food businesses — suitable for a wide variety of dishes. Carefully cultivated and handled to maintain freshness and quality.",
    "ingredients": "100% Fresh Oyster Mushrooms.",
    "benefits": [
      "Harvested at our farm in Odisha",
      "Carefully handled for freshness",
      "Guaranteed freshness & quality"
    ],
    "usage": "Rinse gently before use. Saute, stir-fry, grill, or add to curries, soups, and rice dishes.",
    "shelfLife": "Refrigerate and consume within a few days of delivery",
    "tags": [
      "Bestseller"
    ],
    "images": [
      "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?q=80&w=800&auto=format&fit=crop"
    ],
    "variants": [
      {
        "name": "250g Pack",
        "price": 149,
        "compareAtPrice": 179,
        "sku": "FR-OY-250",
        "stock": 18
      },
      {
        "name": "500g Pack",
        "price": 279,
        "compareAtPrice": 329,
        "sku": "FR-OY-500",
        "stock": 12
      }
    ],
    "status": "active"
  },
  {
    "id": "prod-102",
    "slug": "fresh-button-mushrooms",
    "name": "Fresh Button Mushrooms",
    "category": "Fresh Mushrooms",
    "categorySlug": "fresh-mushrooms",
    "price": 129,
    "compareAtPrice": 159,
    "stock": 40,
    "sku": "FR-BT-500",
    "rating": 4.7,
    "reviewCount": 19,
    "shortDescription": "Fresh white button mushrooms, grown and handled with care.",
    "longDescription": "Fresh white button mushrooms from our farm in Odisha — an everyday ingredient for homes and food businesses. Grown with attention and proper care at every stage, then carefully handled to maintain freshness and quality.",
    "ingredients": "100% Fresh Button Mushrooms.",
    "benefits": [
      "Grown at our farm in Odisha",
      "Careful handling at every stage",
      "Guaranteed freshness & quality"
    ],
    "usage": "Rinse gently before use. Ideal for gravies, pizzas, sandwiches, stir-fries, and soups.",
    "shelfLife": "Refrigerate and consume within a few days of delivery",
    "tags": [
      "New"
    ],
    "images": [
      "https://images.unsplash.com/photo-1608686207856-001b95cf60ca?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?q=80&w=800&auto=format&fit=crop"
    ],
    "variants": [
      {
        "name": "250g Pack",
        "price": 129,
        "compareAtPrice": 159,
        "sku": "FR-BT-250",
        "stock": 22
      },
      {
        "name": "500g Pack",
        "price": 239,
        "compareAtPrice": 289,
        "sku": "FR-BT-500",
        "stock": 18
      }
    ],
    "status": "active"
  },
  {
    "id": "prod-103",
    "slug": "oyster-mushroom-spawn",
    "name": "Oyster Mushroom Spawn",
    "category": "Mushroom Spawn",
    "categorySlug": "mushroom-spawn",
    "price": 299,
    "compareAtPrice": 349,
    "stock": 50,
    "sku": "SP-OY-1KG",
    "rating": 4.9,
    "reviewCount": 34,
    "shortDescription": "Essential starting material for mushroom cultivation, for growers and enthusiasts.",
    "longDescription": "Mushroom spawn is the essential starting material for mushroom cultivation. Produced by our team with years of hands-on experience in the mushroom industry, this spawn is intended for growers and customers interested in cultivating mushrooms themselves.",
    "ingredients": "Oyster mushroom spawn on sterilised grain.",
    "benefits": [
      "Produced with 15 years of cultivation experience",
      "The essential start material for cultivation",
      "For growers and home cultivators"
    ],
    "usage": "Inoculate your prepared substrate or growing medium as per standard cultivation practice.",
    "shelfLife": "Use within 7 days of delivery. Store in a cool, dry place away from sunlight.",
    "tags": [
      "Bestseller",
      "New"
    ],
    "images": [
      "https://images.unsplash.com/photo-1608686207856-001b95cf60ca?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop"
    ],
    "variants": [
      {
        "name": "500g Bag",
        "price": 179,
        "compareAtPrice": 219,
        "sku": "SP-OY-500",
        "stock": 25
      },
      {
        "name": "1kg Bag",
        "price": 299,
        "compareAtPrice": 349,
        "sku": "SP-OY-1KG",
        "stock": 25
      }
    ],
    "status": "active"
  },
  {
    "id": "prod-104",
    "slug": "button-mushroom-spawn",
    "name": "Button Mushroom Spawn",
    "category": "Mushroom Spawn",
    "categorySlug": "mushroom-spawn",
    "price": 279,
    "compareAtPrice": 329,
    "stock": 45,
    "sku": "SP-BT-1KG",
    "rating": 4.8,
    "reviewCount": 21,
    "shortDescription": "Button mushroom spawn for cultivation — an essential part of our work.",
    "longDescription": "Spawn is an essential starting material for mushroom cultivation, and our experience in the mushroom industry gives this category an important place in our company. Intended for growers and customers interested in mushroom cultivation.",
    "ingredients": "Button mushroom spawn on sterilised grain.",
    "benefits": [
      "Produced with 15 years of cultivation experience",
      "The essential start material for cultivation",
      "For growers and home cultivators"
    ],
    "usage": "Inoculate your prepared substrate or growing medium as per standard cultivation practice.",
    "shelfLife": "Use within 7 days of delivery. Store in a cool, dry place away from sunlight.",
    "tags": [],
    "images": [
      "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1608686207856-001b95cf60ca?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop"
    ],
    "variants": [
      {
        "name": "1kg Bag",
        "price": 279,
        "compareAtPrice": 329,
        "sku": "SP-BT-1KG",
        "stock": 45
      }
    ],
    "status": "active"
  },
  {
    "id": "prod-105",
    "slug": "mushroom-powder",
    "name": "Mushroom Powder",
    "category": "Mushroom Powder",
    "categorySlug": "mushroom-powder",
    "price": 449,
    "compareAtPrice": 549,
    "stock": 45,
    "sku": "MP-100",
    "rating": 4.8,
    "reviewCount": 31,
    "shortDescription": "A convenient way to incorporate mushrooms into everyday foods and recipes.",
    "longDescription": "Mushroom powder is a convenient way to incorporate mushrooms into different foods and recipes. It can be used as an ingredient in cooking and adds mushroom flavour to a variety of dishes — part of our effort to create convenient, versatile mushroom-based products for customers.",
    "ingredients": "100% Dried Mushrooms, ground.",
    "benefits": [
      "100% mushroom-based",
      "Convenient everyday ingredient",
      "Adds mushroom flavour to any dish"
    ],
    "usage": "Add 1 tsp to soups, gravies, dals, smoothies, or doughs while cooking.",
    "shelfLife": "Shelf life as marked on pack. Store in an airtight container.",
    "tags": [
      "Bestseller"
    ],
    "images": [
      "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1514733670139-4d87a1941d55?q=80&w=800&auto=format&fit=crop"
    ],
    "variants": [
      {
        "name": "100g Pouch",
        "price": 449,
        "compareAtPrice": 549,
        "sku": "MP-100",
        "stock": 25
      },
      {
        "name": "250g Pouch",
        "price": 999,
        "compareAtPrice": 1199,
        "sku": "MP-250",
        "stock": 20
      }
    ],
    "status": "active"
  },
  {
    "id": "prod-106",
    "slug": "oyster-mushroom-pickle",
    "name": "Oyster Mushroom Pickle",
    "category": "Mushroom Pickle",
    "categorySlug": "mushroom-pickle",
    "price": 349,
    "compareAtPrice": 425,
    "stock": 60,
    "sku": "PK-OY-250",
    "rating": 4.9,
    "reviewCount": 44,
    "shortDescription": "Mushrooms in a traditional and flavourful pickle form.",
    "longDescription": "Mushroom pickle brings mushrooms into a traditional and flavourful form — a different way to enjoy mushrooms as part of your meals. One of our value-added mushroom products, created to offer something different from fresh mushrooms.",
    "ingredients": "Fresh Oyster Mushrooms, Mustard Oil, Spices & Salt.",
    "benefits": [
      "Traditional flavourful format",
      "A value-added mushroom product",
      "Great with rice and Indian bread"
    ],
    "usage": "Serve alongside hot rice, parathas, or any meal of your choice.",
    "shelfLife": "Shelf life as marked on pack. Store in a cool, dry place.",
    "tags": [
      "Bestseller"
    ],
    "images": [
      "https://images.unsplash.com/photo-1534483509719-3feaee7c30da?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?q=80&w=800&auto=format&fit=crop"
    ],
    "variants": [
      {
        "name": "250g Jar",
        "price": 349,
        "compareAtPrice": 425,
        "sku": "PK-OY-250",
        "stock": 35
      },
      {
        "name": "500g Jar",
        "price": 629,
        "compareAtPrice": 749,
        "sku": "PK-OY-500",
        "stock": 25
      }
    ],
    "status": "active"
  },
  {
    "id": "prod-107",
    "slug": "button-mushroom-pickle",
    "name": "Button Mushroom Pickle",
    "category": "Mushroom Pickle",
    "categorySlug": "mushroom-pickle",
    "price": 329,
    "compareAtPrice": 399,
    "stock": 40,
    "sku": "PK-BT-250",
    "rating": 4.7,
    "reviewCount": 27,
    "shortDescription": "A value-added mushroom product in a familiar, flavourful form.",
    "longDescription": "A flavourful mushroom pickle made from fresh button mushrooms — part of our range of value-added mushroom products. It offers customers a different way to enjoy mushrooms alongside their everyday meals.",
    "ingredients": "Fresh Button Mushrooms, Mustard Oil, Spices & Salt.",
    "benefits": [
      "Traditional flavourful format",
      "A value-added mushroom product",
      "Made from fresh farm mushrooms"
    ],
    "usage": "Serve alongside hot rice, parathas, or any meal of your choice.",
    "shelfLife": "Shelf life as marked on pack. Store in a cool, dry place.",
    "tags": [],
    "images": [
      "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1534483509719-3feaee7c30da?q=80&w=800&auto=format&fit=crop"
    ],
    "variants": [
      {
        "name": "250g Jar",
        "price": 329,
        "compareAtPrice": 399,
        "sku": "PK-BT-250",
        "stock": 25
      },
      {
        "name": "500g Jar",
        "price": 599,
        "compareAtPrice": 699,
        "sku": "PK-BT-500",
        "stock": 15
      }
    ],
    "status": "active"
  },
  {
    "id": "prod-108",
    "slug": "sun-dried-oyster-mushrooms",
    "name": "Sun-Dried Oyster Mushrooms",
    "category": "Sun-Dried Mushrooms",
    "categorySlug": "sun-dried-mushrooms",
    "price": 399,
    "compareAtPrice": 479,
    "stock": 40,
    "sku": "SD-OY-100",
    "rating": 4.8,
    "reviewCount": 29,
    "shortDescription": "Dried oyster mushrooms for storage and use across many types of cooking.",
    "longDescription": "Our sun-dried mushroom products provide another way to enjoy mushrooms beyond their fresh form. Drying allows mushrooms to be stored and used across different types of cooking — a convenient mushroom option for any kitchen.",
    "ingredients": "100% Sun-Dried Oyster Mushrooms.",
    "benefits": [
      "Store and use across many types of cooking",
      "Concentrated mushroom flavour",
      "A convenient pantry staple"
    ],
    "usage": "Rehydrate in warm water for 10–15 minutes before adding to curries, stir-fries, and soups.",
    "shelfLife": "Shelf life as marked on pack. Store in an airtight container.",
    "tags": [
      "New"
    ],
    "images": [
      "https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop"
    ],
    "variants": [
      {
        "name": "100g Pouch",
        "price": 399,
        "compareAtPrice": 479,
        "sku": "SD-OY-100",
        "stock": 25
      },
      {
        "name": "250g Pouch",
        "price": 849,
        "compareAtPrice": 999,
        "sku": "SD-OY-250",
        "stock": 15
      }
    ],
    "status": "active"
  },
  {
    "id": "prod-109",
    "slug": "sun-dried-shiitake-mushrooms",
    "name": "Sun-Dried Shiitake Mushrooms",
    "category": "Sun-Dried Mushrooms",
    "categorySlug": "sun-dried-mushrooms",
    "price": 499,
    "compareAtPrice": 599,
    "stock": 35,
    "sku": "SD-SH-100",
    "rating": 4.9,
    "reviewCount": 36,
    "shortDescription": "Dried shiitake mushrooms that store well and cook beautifully.",
    "longDescription": "Sun-dried shiitake mushrooms — another convenient way to enjoy mushrooms beyond their fresh form. Drying allows them to be stored and used in different types of cooking, from rice dishes to gravies and soups.",
    "ingredients": "100% Sun-Dried Shiitake Mushrooms.",
    "benefits": [
      "Store and use across many types of cooking",
      "Concentrated mushroom flavour",
      "A convenient pantry staple"
    ],
    "usage": "Rehydrate in warm water for 15–20 minutes before adding to your cooking. Use the soaking liquid as stock.",
    "shelfLife": "Shelf life as marked on pack. Store in an airtight container.",
    "tags": [
      "Bestseller"
    ],
    "images": [
      "https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=800&auto=format&fit=crop"
    ],
    "variants": [
      {
        "name": "100g Pouch",
        "price": 499,
        "compareAtPrice": 599,
        "sku": "SD-SH-100",
        "stock": 25
      },
      {
        "name": "250g Pouch",
        "price": 1099,
        "compareAtPrice": 1299,
        "sku": "SD-SH-250",
        "stock": 10
      }
    ],
    "status": "active"
  },
  {
    "id": "prod-110",
    "slug": "mushroom-soup-mix",
    "name": "Mushroom Soup Mix",
    "category": "Mushroom Soup Mix",
    "categorySlug": "mushroom-soup-mix",
    "price": 349,
    "compareAtPrice": 429,
    "stock": 45,
    "sku": "SP-200",
    "rating": 4.7,
    "reviewCount": 24,
    "shortDescription": "A convenient way to prepare mushroom soup at home.",
    "longDescription": "Our mushroom soup mix is designed for customers looking for a convenient mushroom-based food option. It provides an easy way to prepare mushroom soup while bringing the flavour of mushrooms into a simple, convenient product.",
    "ingredients": "Dried Mushroom Powder, Spices & Seasoning.",
    "benefits": [
      "Easy way to prepare mushroom soup",
      "A convenient everyday option",
      "Brings mushroom flavour to a simple meal"
    ],
    "usage": "Stir into hot water or milk, simmer for a few minutes while stirring, and serve hot.",
    "shelfLife": "Shelf life as marked on pack. Store in an airtight container.",
    "tags": [],
    "images": [
      "https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1547592180-85f173990554?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=800&auto=format&fit=crop"
    ],
    "variants": [
      {
        "name": "200g Pouch",
        "price": 349,
        "compareAtPrice": 429,
        "sku": "SP-200",
        "stock": 30
      },
      {
        "name": "500g Pouch",
        "price": 749,
        "compareAtPrice": 899,
        "sku": "SP-500",
        "stock": 15
      }
    ],
    "status": "active"
  },
  {
    "id": "prod-111",
    "slug": "mushroom-chutney",
    "name": "Mushroom Chutney",
    "category": "Mushroom Chutney",
    "categorySlug": "mushroom-chutney",
    "price": 299,
    "compareAtPrice": 349,
    "stock": 55,
    "sku": "CH-220",
    "rating": 4.8,
    "reviewCount": 38,
    "shortDescription": "A familiar and enjoyable food format for mushroom lovers.",
    "longDescription": "Mushroom chutney is another value-added product in our range. It combines the versatility of mushrooms with a familiar and enjoyable food format — served as an accompaniment with meals, it gives customers another way to enjoy mushroom-based food.",
    "ingredients": "Mushrooms, Spices, Oil & Salt.",
    "benefits": [
      "Familiar, enjoyable accompaniment",
      "A value-added mushroom product",
      "Serves with meals of all kinds"
    ],
    "usage": "Serve as an accompaniment with rice, roti, dosa, sandwiches, or snacks.",
    "shelfLife": "Shelf life as marked on pack. Store in a cool, dry place.",
    "tags": [
      "Bestseller"
    ],
    "images": [
      "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1534483509719-3feaee7c30da?q=80&w=800&auto=format&fit=crop"
    ],
    "variants": [
      {
        "name": "220g Jar",
        "price": 299,
        "compareAtPrice": 349,
        "sku": "CH-220",
        "stock": 35
      },
      {
        "name": "450g Jar",
        "price": 549,
        "compareAtPrice": 649,
        "sku": "CH-450",
        "stock": 20
      }
    ],
    "status": "active"
  },
  {
    "id": "prod-112",
    "slug": "oyster-home-growing-kit",
    "name": "Oyster Mushroom Home Growing Kit",
    "category": "Home Growing Kit",
    "categorySlug": "home-growing-kit",
    "price": 699,
    "compareAtPrice": 899,
    "stock": 20,
    "sku": "GK-OY-01",
    "rating": 4.9,
    "reviewCount": 52,
    "shortDescription": "An accessible way to experience mushroom cultivation at home.",
    "longDescription": "For people interested in experiencing mushroom cultivation themselves, our Home Growing Kit provides an accessible way to explore growing mushrooms at home. Mushroom cultivation should not only be something people see on a farm — it can also be an interesting experience for anyone who wants to understand how mushrooms grow and enjoy the process themselves.",
    "ingredients": "Pre-spawned growing block, misting bottle & instruction booklet.",
    "benefits": [
      "Experience cultivation at your home",
      "Understand how mushrooms grow",
      "Accessible for beginners"
    ],
    "usage": "Open the kit as directed, mist with clean water, and watch your fresh mushrooms grow.",
    "shelfLife": "Use within 60 days of delivery",
    "tags": [
      "Bestseller"
    ],
    "images": [
      "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?q=80&w=800&auto=format&fit=crop"
    ],
    "variants": [
      {
        "name": "Single Grow Kit",
        "price": 699,
        "compareAtPrice": 899,
        "sku": "GK-OY-01",
        "stock": 12
      },
      {
        "name": "Duo Grow Kit",
        "price": 1299,
        "compareAtPrice": 1599,
        "sku": "GK-OY-02",
        "stock": 8
      }
    ],
    "status": "active"
  },
  {
    "id": "prod-113",
    "slug": "farm-combo-pack",
    "name": "Farm Combo Pack",
    "category": "Farm Combo Pack",
    "categorySlug": "farm-combo-pack",
    "price": 999,
    "compareAtPrice": 1199,
    "stock": 25,
    "sku": "CB-FM-01",
    "rating": 4.9,
    "reviewCount": 22,
    "shortDescription": "Selected mushroom products together in one convenient package.",
    "longDescription": "Our Farm Combo Pack brings selected mushroom products together in one convenient package. It is designed for customers who want to explore more than one product from our range — a convenient way to experience different products from our mushroom business.",
    "ingredients": "Assorted mushroom products from our range. See pack for contents.",
    "benefits": [
      "Explore more than one product",
      "Selected products in one package",
      "A convenient way to try our range"
    ],
    "usage": "Gift it or enjoy across daily meals — from breakfast to dinner.",
    "shelfLife": "Shelf life as marked on pack",
    "tags": [
      "Bestseller"
    ],
    "images": [
      "https://images.unsplash.com/photo-1608686207856-001b95cf60ca?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1534483509719-3feaee7c30da?q=80&w=800&auto=format&fit=crop"
    ],
    "variants": [
      {
        "name": "Combo Pack",
        "price": 999,
        "compareAtPrice": 1199,
        "sku": "CB-FM-01",
        "stock": 25
      }
    ],
    "status": "active"
  }
]'::jsonb) as e(value)
on conflict (id) do update set data = excluded.data;

insert into public.categories (id, data)
select e.value ->> 'id', e.value
from jsonb_array_elements('[
  {
    "id": "cat-1",
    "name": "Fresh Mushrooms",
    "slug": "fresh-mushrooms",
    "description": "Fresh mushrooms for everyday cooking and food preparation.",
    "image": "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop",
    "featured": true,
    "itemCount": 2
  },
  {
    "id": "cat-2",
    "name": "Mushroom Spawn",
    "slug": "mushroom-spawn",
    "description": "The essential starting material for mushroom cultivation.",
    "image": "https://images.unsplash.com/photo-1608686207856-001b95cf60ca?q=80&w=800&auto=format&fit=crop",
    "featured": true,
    "itemCount": 2
  },
  {
    "id": "cat-3",
    "name": "Mushroom Powder",
    "slug": "mushroom-powder",
    "description": "A convenient way to add mushroom flavour to cooking and recipes.",
    "image": "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?q=80&w=800&auto=format&fit=crop",
    "featured": true,
    "itemCount": 1
  },
  {
    "id": "cat-4",
    "name": "Mushroom Pickle",
    "slug": "mushroom-pickle",
    "description": "A traditional, flavourful form — a value-added mushroom product.",
    "image": "https://images.unsplash.com/photo-1534483509719-3feaee7c30da?q=80&w=800&auto=format&fit=crop",
    "featured": true,
    "itemCount": 2
  },
  {
    "id": "cat-5",
    "name": "Sun-Dried Mushrooms",
    "slug": "sun-dried-mushrooms",
    "description": "Dried for storage and use across many types of cooking.",
    "image": "https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?q=80&w=800&auto=format&fit=crop",
    "featured": true,
    "itemCount": 2
  },
  {
    "id": "cat-6",
    "name": "Mushroom Soup Mix",
    "slug": "mushroom-soup-mix",
    "description": "An easy way to prepare mushroom soup at home.",
    "image": "https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800&auto=format&fit=crop",
    "featured": false,
    "itemCount": 1
  },
  {
    "id": "cat-7",
    "name": "Mushroom Chutney",
    "slug": "mushroom-chutney",
    "description": "A familiar accompaniment that combines mushrooms with an everyday format.",
    "image": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=800&auto=format&fit=crop",
    "featured": false,
    "itemCount": 1
  },
  {
    "id": "cat-8",
    "name": "Home Growing Kit",
    "slug": "home-growing-kit",
    "description": "An accessible way to experience mushroom cultivation at home.",
    "image": "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop",
    "featured": true,
    "itemCount": 1
  },
  {
    "id": "cat-9",
    "name": "Farm Combo Pack",
    "slug": "farm-combo-pack",
    "description": "Selected mushroom products together in one convenient package.",
    "image": "https://images.unsplash.com/photo-1608686207856-001b95cf60ca?q=80&w=800&auto=format&fit=crop",
    "featured": true,
    "itemCount": 1
  }
]'::jsonb) as e(value)
on conflict (id) do update set data = excluded.data;

insert into public.coupons (id, data)
select e.value ->> 'id', e.value
from jsonb_array_elements('[
  {
    "id": "coup-1",
    "code": "WELCOME10",
    "discountType": "percentage",
    "discountValue": 10,
    "minOrderAmount": 499,
    "maxDiscount": 200,
    "expiryDate": "2026-12-31",
    "usageLimit": 1000,
    "usedCount": 142,
    "active": true,
    "description": "10% Off on your first order over ₹499"
  },
  {
    "id": "coup-2",
    "code": "FUNGI15",
    "discountType": "percentage",
    "discountValue": 15,
    "minOrderAmount": 1499,
    "maxDiscount": 500,
    "expiryDate": "2026-11-30",
    "usageLimit": 500,
    "usedCount": 89,
    "active": true,
    "description": "15% Off on premium harvests over ₹1499"
  },
  {
    "id": "coup-3",
    "code": "FARMFLAT200",
    "discountType": "flat",
    "discountValue": 200,
    "minOrderAmount": 1999,
    "maxDiscount": 200,
    "expiryDate": "2026-10-31",
    "usageLimit": 250,
    "usedCount": 45,
    "active": true,
    "description": "Flat ₹200 discount on combo packs & bulk orders"
  }
]'::jsonb) as e(value)
on conflict (id) do update set data = excluded.data;

insert into public.reviews (id, data)
select e.value ->> 'id', e.value
from jsonb_array_elements('[
  {
    "id": "rev-1",
    "productId": "prod-101",
    "productName": "Fresh Oyster Mushrooms",
    "author": "Ananya Iyer",
    "rating": 5,
    "date": "2026-09-15",
    "verifiedPurchase": true,
    "status": "approved",
    "title": "Fresh and carefully packed",
    "content": "The oyster mushrooms arrived clean and fresh. Cooked beautifully in a simple stir-fry. You can tell they are handled with care."
  },
  {
    "id": "rev-2",
    "productId": "prod-106",
    "productName": "Oyster Mushroom Pickle",
    "author": "Rajesh K.",
    "rating": 5,
    "date": "2026-09-20",
    "verifiedPurchase": true,
    "status": "approved",
    "title": "A different way to enjoy mushrooms",
    "content": "Traditional flavour, not too heavy, and the mushroom pieces stay firm. Goes very well with hot rice. Ordering again."
  },
  {
    "id": "rev-3",
    "productId": "prod-112",
    "productName": "Oyster Mushroom Home Growing Kit",
    "author": "Meera Nair",
    "rating": 5,
    "date": "2026-09-22",
    "verifiedPurchase": true,
    "status": "approved",
    "title": "Fascinating to watch mushrooms grow",
    "content": "The kit was easy to follow and it was genuinely interesting to see the full growing process at home. Great experience for the family."
  },
  {
    "id": "rev-4",
    "productId": "prod-109",
    "productName": "Sun-Dried Shiitake Mushrooms",
    "author": "Chef Devendra P.",
    "rating": 4,
    "date": "2026-09-25",
    "verifiedPurchase": true,
    "status": "approved",
    "title": "Convenient pantry staple",
    "content": "Rehydrated well and the flavour was deep and mushroomy. The soaking liquid made a lovely base for stock. Good quality dried mushrooms."
  }
]'::jsonb) as e(value)
on conflict (id) do update set data = excluded.data;

insert into public.blogs (id, data)
select e.value ->> 'id', e.value
from jsonb_array_elements('[
  {
    "id": "blog-1",
    "slug": "15-years-of-experience-one-passion",
    "title": "15 Years of Experience. One Passion.",
    "excerpt": "The story of MANASI MUSHROOM & SPAWN PVT. LTD. — how Mrs. Manasi Pattanayak''s hands-on work in mushroom cultivation became a growing company.",
    "category": "Our Journey",
    "author": "Team MANASI",
    "date": "Sep 18, 2026",
    "readTime": "5 min read",
    "image": "https://images.unsplash.com/photo-1547592180-85f173990554?q=80&w=800&auto=format&fit=crop",
    "featured": true,
    "content": "\n      <p>The story of MANASI MUSHROOM &amp; SPAWN PVT. LTD. began with Mrs. Manasi Pattanayak, the founder behind our journey. With 15 years of experience in mushroom cultivation and the mushroom industry, she has developed valuable practical knowledge through years of working directly with mushrooms — cultivation, production, handling, and mushroom-based products.</p>\n      <h3>From Cultivation to a Structured Business</h3>\n      <p>What started as a journey in mushroom cultivation gradually developed into a larger vision. Years of experience, learning, experimentation, and dedication created the foundation for building a professionally structured mushroom business.</p>\n      <h3>A New Chapter in 2026</h3>\n      <p>In 2026, this journey took an important step forward when the business was officially registered as MANASI MUSHROOM &amp; SPAWN PVT. LTD. This new chapter represents the combination of years of practical experience with a growing vision for the future — serving customers across India with trust.</p>\n    "
  },
  {
    "id": "blog-2",
    "slug": "how-our-farm-works",
    "title": "From Our Farm: How Cultivation, Care & Products Come Together",
    "excerpt": "A look at our farm in Pedagadi, Udala, Mayurbhanj, Odisha — where every cultivation cycle begins with attention and proper care.",
    "category": "Farm & Field",
    "author": "Team MANASI",
    "date": "Sep 10, 2026",
    "readTime": "6 min read",
    "image": "https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=800&auto=format&fit=crop",
    "featured": true,
    "content": "\n      <p>Our farm is the heart of MANASI MUSHROOM &amp; SPAWN PVT. LTD. Located in Pedagadi, Udala, Mayurbhanj, Odisha, it is where our journey with mushrooms comes to life and where every cultivation cycle requires attention and proper care.</p>\n      <h3>Care at Every Stage</h3>\n      <p>Every cycle follows the same disciplined path: preparing the growing environment, monitoring mushroom growth, and carefully handling the final produce. Good products begin with proper cultivation and careful handling at the farm level.</p>\n      <h3>From Farm to Products</h3>\n      <p>From cultivation to processing, our farm is the starting point of many of our mushroom products. Fresh mushrooms, mushroom spawn, and other mushroom-based products are all connected to the knowledge and experience developed through our work in cultivation.</p>\n    "
  },
  {
    "id": "blog-3",
    "slug": "mushrooms-in-everyday-cooking",
    "title": "Mushrooms in Everyday Cooking: Powder, Pickle, Soup Mix & More",
    "excerpt": "Different ways to enjoy mushrooms at home — from fresh cooking to convenient mushroom-based products for everyday use.",
    "category": "Kitchen Notes",
    "author": "Team MANASI",
    "date": "Aug 28, 2026",
    "readTime": "4 min read",
    "image": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800&auto=format&fit=crop",
    "featured": false,
    "content": "\n      <p>Mushrooms are a versatile ingredient for homes, restaurants, and food businesses. Our product range is designed to provide different ways to enjoy and explore mushrooms in everyday cooking.</p>\n      <h3>Many Forms, One Ingredient</h3>\n      <p>Fresh mushrooms can be used in a wide variety of dishes. Sun-dried mushrooms can be stored and used across different types of cooking, while mushroom powder adds mushroom flavour to soups, gravies, and doughs with a simple spoonful.</p>\n      <h3>Convenient, Value-Added Products</h3>\n      <p>Mushroom pickle and mushroom chutney bring mushrooms into familiar, flavourful formats to serve alongside meals. Our mushroom soup mix offers an easy way to prepare mushroom soup at home — convenient food options that bring the flavour of mushrooms to the table.</p>\n    "
  }
]'::jsonb) as e(value)
on conflict (id) do update set data = excluded.data;

insert into public.banners (id, data)
select e.value ->> 'id', e.value
from jsonb_array_elements('[
  {
    "id": "ban-1",
    "title": "Fresh Mushrooms. Healthy Life.",
    "subtitle": "Cultivated, processed & packed by MANASI MUSHROOM & SPAWN PVT. LTD.",
    "ctaText": "Explore Collection",
    "ctaLink": "/shop",
    "image": "https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=1200&auto=format&fit=crop",
    "active": true,
    "position": "hero-1"
  },
  {
    "id": "ban-2",
    "title": "Supplying Across India With Trust.",
    "subtitle": "From our farm in Odisha — guaranteed freshness & quality.",
    "ctaText": "Our Farm",
    "ctaLink": "/our-farm",
    "image": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1200&auto=format&fit=crop",
    "active": true,
    "position": "hero-2"
  },
  {
    "id": "ban-3",
    "title": "Grow Mushrooms At Home",
    "subtitle": "Home growing kits & mushroom spawn for every kind of grower",
    "ctaText": "Shop Growing Supplies",
    "ctaLink": "/category/home-growing-kit",
    "image": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?q=80&w=1200&auto=format&fit=crop",
    "active": true,
    "position": "promo-banner"
  }
]'::jsonb) as e(value)
on conflict (id) do update set data = excluded.data;

insert into public.faqs (id, data)
select e.value ->> 'id', e.value
from jsonb_array_elements('[
  {
    "id": "faq-1",
    "question": "Who is MANASI MUSHROOM & SPAWN PVT. LTD.?",
    "answer": "We are a mushroom-focused company built on experience, dedication, quality, and a strong connection with mushroom cultivation. Founded by Mrs. Manasi Pattanayak, who has 15 years of experience in mushroom cultivation and the mushroom industry, the company was officially registered in 2026. Our roots are in Pedagadi, Udala, Mayurbhanj, Odisha."
  },
  {
    "id": "faq-2",
    "question": "What products do you offer?",
    "answer": "Our work covers mushroom cultivation, mushroom spawn production, and mushroom-based food products. Our range includes fresh mushrooms, mushroom spawn, sun-dried mushrooms, mushroom powder, mushroom pickle, mushroom soup mix, mushroom chutney, a home growing kit, and a farm combo pack."
  },
  {
    "id": "faq-3",
    "question": "Where is your farm located?",
    "answer": "Our farm is located in Pedagadi, Udala, Mayurbhanj, Odisha. It is the heart of our company and the starting point of many of our mushroom products — from fresh mushrooms and spawn to processed products."
  },
  {
    "id": "faq-4",
    "question": "Do you ship across India?",
    "answer": "Yes — our brand line is ''Supplying Across India With Trust.'' We work toward serving customers from different parts of India. Orders over ₹999 qualify for complimentary shipping on this store."
  },
  {
    "id": "faq-5",
    "question": "Do you sell spawn and home growing kits?",
    "answer": "Yes. Mushroom spawn is an essential starting material for mushroom cultivation and is intended for growers and customers interested in cultivation. Our Home Growing Kit offers an accessible way to experience growing mushrooms at home."
  }
]'::jsonb) as e(value)
on conflict (id) do update set data = excluded.data;

insert into public.customers (id, data)
select e.value ->> 'id', e.value
from jsonb_array_elements('[
  {
    "id": "cust-1",
    "name": "Aarav Sharma",
    "email": "aarav.sharma@example.com",
    "phone": "+91 98123 45678",
    "ordersCount": 4,
    "totalSpent": 7850,
    "status": "active",
    "joinDate": "2026-03-12",
    "addresses": [
      {
        "id": "addr-1",
        "label": "Home",
        "name": "Aarav Sharma",
        "phone": "+91 98123 45678",
        "street": "42 Golf Links, Apartment 3B",
        "city": "New Delhi",
        "state": "Delhi",
        "pincode": "110003",
        "isDefault": true
      }
    ]
  },
  {
    "id": "cust-2",
    "name": "Priyanjali Sen",
    "email": "priya.sen@example.com",
    "phone": "+91 97654 32109",
    "ordersCount": 2,
    "totalSpent": 3120,
    "status": "active",
    "joinDate": "2026-05-20",
    "addresses": [
      {
        "id": "addr-2",
        "label": "Office",
        "name": "Priyanjali Sen",
        "phone": "+91 97654 32109",
        "street": "18 Jubilee Hills, Road No 10",
        "city": "Hyderabad",
        "state": "Telangana",
        "pincode": "500033",
        "isDefault": true
      }
    ]
  },
  {
    "id": "cust-3",
    "name": "Vikramaditya Roy",
    "email": "vikram.roy@example.com",
    "phone": "+91 99887 76655",
    "ordersCount": 1,
    "totalSpent": 3306,
    "status": "active",
    "joinDate": "2026-09-01",
    "addresses": [
      {
        "id": "addr-3",
        "label": "Home",
        "name": "Vikramaditya Roy",
        "phone": "+91 99887 76655",
        "street": "75 Koregaon Park, Lane 4",
        "city": "Pune",
        "state": "Maharashtra",
        "pincode": "411001",
        "isDefault": true
      }
    ]
  }
]'::jsonb) as e(value)
on conflict (id) do update set data = excluded.data;

insert into public.messages (id, data)
select e.value ->> 'id', e.value
from jsonb_array_elements('[
  {
    "id": "msg-1",
    "name": "Devika Malhotra",
    "email": "devika@example.com",
    "phone": "+91 98765 11223",
    "subject": "Bulk Mushroom Powder & Spawn Inquiry",
    "message": "Hello, we operate a restaurant chain in Bengaluru and would like to enquire about wholesale pricing for mushroom powder and fresh mushrooms, plus spawn for our own growing unit.",
    "date": "2026-09-29T16:20:00.000Z",
    "read": false
  }
]'::jsonb) as e(value)
on conflict (id) do update set data = excluded.data;

insert into public.subscribers (id, data)
select e.value ->> 'id', e.value
from jsonb_array_elements('[
  {
    "id": "sub-1",
    "email": "gourmet.lover@example.com",
    "date": "2026-09-15"
  },
  {
    "id": "sub-2",
    "email": "culinary.chef@example.com",
    "date": "2026-09-22"
  }
]'::jsonb) as e(value)
on conflict (id) do update set data = excluded.data;

insert into public.settings (key, data)
select e.key, e.value
from jsonb_each('{
  "site_config": {
    "name": "MANASI MUSHROOM",
    "tagline": "15 Years of Experience. One Passion.",
    "logoText": "MANASI",
    "subtitle": "Supplying Across India with Trust",
    "currencySymbol": "₹",
    "currencyCode": "INR",
    "gstPercentage": 5,
    "freeShippingThreshold": 999,
    "defaultShippingFee": 99,
    "phone": "+91 98765 43210",
    "whatsapp": "+919876543210",
    "email": "concierge@brandname.com",
    "address": "Pedagadi, Udala, Mayurbhanj, Odisha, India",
    "hours": "Mon - Sat: 9:00 AM - 7:00 PM IST",
    "socials": {
      "instagram": "https://instagram.com/brandname",
      "facebook": "https://facebook.com/brandname",
      "pinterest": "https://pinterest.com/brandname",
      "youtube": "https://youtube.com/brandname"
    },
    "announcementText": "Complimentary Express Shipping on orders over ₹999 | Handcrafted Harvest",
    "aboutShort": "MANASI MUSHROOM & SPAWN PVT. LTD. is a mushroom-focused company built on experience, dedication, quality, and a strong connection with mushroom cultivation — rooted in Pedagadi, Udala, Mayurbhanj, Odisha, and serving customers across India.",
    "farmStory": "Our journey began with 15 years of hands-on mushroom cultivation. From our farm in Odisha, every cycle is guided by attention and proper care — from preparing the growing environment to handling the final produce."
  },
  "shipping_tax": {
    "gstPercentage": 5,
    "freeShippingThreshold": 999,
    "flatShippingFee": 99,
    "pincodes": [
      "110001",
      "110003",
      "411001",
      "500033",
      "400001",
      "560001",
      "600001",
      "700001",
      "173212"
    ]
  }
}'::jsonb) as e(key, value)
on conflict (key) do update set data = excluded.data, updated_at = now();

insert into public.orders (id, user_id, customer_email, status, total, date, data)
select
  o.value ->> 'id',
  null,
  o.value -> 'customer' ->> 'email',
  coalesce(o.value ->> 'status', 'Placed'),
  coalesce((o.value ->> 'total')::numeric, 0),
  (o.value ->> 'date')::timestamptz,
  o.value
from jsonb_array_elements('[
  {
    "id": "ORD-89241",
    "date": "2026-09-28T14:32:00.000Z",
    "customer": {
      "name": "Aarav Sharma",
      "email": "aarav.sharma@example.com",
      "phone": "+91 98123 45678",
      "address": "42 Golf Links, Apartment 3B",
      "city": "New Delhi",
      "state": "Delhi",
      "pincode": "110003"
    },
    "items": [
      {
        "id": "prod-105",
        "name": "Mushroom Powder",
        "variant": "100g Pouch",
        "price": 449,
        "quantity": 2,
        "image": "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?q=80&w=800&auto=format&fit=crop"
      },
      {
        "id": "prod-106",
        "name": "Oyster Mushroom Pickle",
        "variant": "250g Jar",
        "price": 349,
        "quantity": 1,
        "image": "https://images.unsplash.com/photo-1534483509719-3feaee7c30da?q=80&w=800&auto=format&fit=crop"
      }
    ],
    "subtotal": 1247,
    "discount": 100,
    "couponCode": "WELCOME10",
    "tax": 57,
    "shippingFee": 0,
    "total": 1204,
    "status": "Delivered",
    "paymentMethod": "UPI",
    "paymentStatus": "Paid",
    "trackingNumber": "TRK-IN-9920148",
    "timeline": [
      {
        "status": "Placed",
        "time": "Sep 28, 02:32 PM",
        "done": true
      },
      {
        "status": "Confirmed",
        "time": "Sep 28, 03:00 PM",
        "done": true
      },
      {
        "status": "Packed",
        "time": "Sep 29, 09:15 AM",
        "done": true
      },
      {
        "status": "Shipped",
        "time": "Sep 29, 02:30 PM",
        "done": true
      },
      {
        "status": "Delivered",
        "time": "Oct 01, 11:20 AM",
        "done": true
      }
    ]
  },
  {
    "id": "ORD-89242",
    "date": "2026-09-30T10:15:00.000Z",
    "customer": {
      "name": "Priyanjali Sen",
      "email": "priya.sen@example.com",
      "phone": "+91 97654 32109",
      "address": "18 Jubilee Hills, Road No 10",
      "city": "Hyderabad",
      "state": "Telangana",
      "pincode": "500033"
    },
    "items": [
      {
        "id": "prod-112",
        "name": "Oyster Mushroom Home Growing Kit",
        "variant": "Single Grow Kit",
        "price": 699,
        "quantity": 1,
        "image": "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop"
      }
    ],
    "subtotal": 699,
    "discount": 0,
    "couponCode": "",
    "tax": 35,
    "shippingFee": 99,
    "total": 833,
    "status": "Shipped",
    "paymentMethod": "Credit Card",
    "paymentStatus": "Paid",
    "trackingNumber": "TRK-IN-9920311",
    "timeline": [
      {
        "status": "Placed",
        "time": "Sep 30, 10:15 AM",
        "done": true
      },
      {
        "status": "Confirmed",
        "time": "Sep 30, 10:30 AM",
        "done": true
      },
      {
        "status": "Packed",
        "time": "Sep 30, 04:00 PM",
        "done": true
      },
      {
        "status": "Shipped",
        "time": "Oct 01, 09:00 AM",
        "done": true
      },
      {
        "status": "Delivered",
        "time": "Expected Oct 03",
        "done": false
      }
    ]
  },
  {
    "id": "ORD-89243",
    "date": "2026-10-01T08:45:00.000Z",
    "customer": {
      "name": "Vikramaditya Roy",
      "email": "vikram.roy@example.com",
      "phone": "+91 99887 76655",
      "address": "75 Koregaon Park, Lane 4",
      "city": "Pune",
      "state": "Maharashtra",
      "pincode": "411001"
    },
    "items": [
      {
        "id": "prod-109",
        "name": "Sun-Dried Shiitake Mushrooms",
        "variant": "100g Pouch",
        "price": 499,
        "quantity": 1,
        "image": "https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?q=80&w=800&auto=format&fit=crop"
      }
    ],
    "subtotal": 499,
    "discount": 0,
    "couponCode": "",
    "tax": 25,
    "shippingFee": 99,
    "total": 623,
    "status": "Confirmed",
    "paymentMethod": "Cash on Delivery",
    "paymentStatus": "Pending",
    "trackingNumber": "TRK-IN-9920405",
    "timeline": [
      {
        "status": "Placed",
        "time": "Oct 01, 08:45 AM",
        "done": true
      },
      {
        "status": "Confirmed",
        "time": "Oct 01, 09:15 AM",
        "done": true
      },
      {
        "status": "Packed",
        "time": "Pending",
        "done": false
      },
      {
        "status": "Shipped",
        "time": "Pending",
        "done": false
      },
      {
        "status": "Delivered",
        "time": "Pending",
        "done": false
      }
    ]
  }
]'::jsonb) as o(value)
on conflict (id) do update set
  status = excluded.status,
  total = excluded.total,
  date = excluded.date,
  customer_email = excluded.customer_email,
  data = excluded.data;

-- Payload used by the admin "Reset Demo Data" RPC
insert into public.seed_payload (key, data)
values ('initial', '{
  "products": [
    {
      "id": "prod-101",
      "slug": "fresh-oyster-mushrooms",
      "name": "Fresh Oyster Mushrooms",
      "category": "Fresh Mushrooms",
      "categorySlug": "fresh-mushrooms",
      "price": 149,
      "compareAtPrice": 179,
      "stock": 30,
      "sku": "FR-OY-500",
      "rating": 4.8,
      "reviewCount": 26,
      "shortDescription": "Fresh oyster mushrooms for everyday cooking and food preparation.",
      "longDescription": "Fresh oyster mushrooms from our farm in Pedagadi, Udala, Mayurbhanj, Odisha. A versatile ingredient for homes, restaurants, and food businesses — suitable for a wide variety of dishes. Carefully cultivated and handled to maintain freshness and quality.",
      "ingredients": "100% Fresh Oyster Mushrooms.",
      "benefits": [
        "Harvested at our farm in Odisha",
        "Carefully handled for freshness",
        "Guaranteed freshness & quality"
      ],
      "usage": "Rinse gently before use. Saute, stir-fry, grill, or add to curries, soups, and rice dishes.",
      "shelfLife": "Refrigerate and consume within a few days of delivery",
      "tags": [
        "Bestseller"
      ],
      "images": [
        "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?q=80&w=800&auto=format&fit=crop"
      ],
      "variants": [
        {
          "name": "250g Pack",
          "price": 149,
          "compareAtPrice": 179,
          "sku": "FR-OY-250",
          "stock": 18
        },
        {
          "name": "500g Pack",
          "price": 279,
          "compareAtPrice": 329,
          "sku": "FR-OY-500",
          "stock": 12
        }
      ],
      "status": "active"
    },
    {
      "id": "prod-102",
      "slug": "fresh-button-mushrooms",
      "name": "Fresh Button Mushrooms",
      "category": "Fresh Mushrooms",
      "categorySlug": "fresh-mushrooms",
      "price": 129,
      "compareAtPrice": 159,
      "stock": 40,
      "sku": "FR-BT-500",
      "rating": 4.7,
      "reviewCount": 19,
      "shortDescription": "Fresh white button mushrooms, grown and handled with care.",
      "longDescription": "Fresh white button mushrooms from our farm in Odisha — an everyday ingredient for homes and food businesses. Grown with attention and proper care at every stage, then carefully handled to maintain freshness and quality.",
      "ingredients": "100% Fresh Button Mushrooms.",
      "benefits": [
        "Grown at our farm in Odisha",
        "Careful handling at every stage",
        "Guaranteed freshness & quality"
      ],
      "usage": "Rinse gently before use. Ideal for gravies, pizzas, sandwiches, stir-fries, and soups.",
      "shelfLife": "Refrigerate and consume within a few days of delivery",
      "tags": [
        "New"
      ],
      "images": [
        "https://images.unsplash.com/photo-1608686207856-001b95cf60ca?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?q=80&w=800&auto=format&fit=crop"
      ],
      "variants": [
        {
          "name": "250g Pack",
          "price": 129,
          "compareAtPrice": 159,
          "sku": "FR-BT-250",
          "stock": 22
        },
        {
          "name": "500g Pack",
          "price": 239,
          "compareAtPrice": 289,
          "sku": "FR-BT-500",
          "stock": 18
        }
      ],
      "status": "active"
    },
    {
      "id": "prod-103",
      "slug": "oyster-mushroom-spawn",
      "name": "Oyster Mushroom Spawn",
      "category": "Mushroom Spawn",
      "categorySlug": "mushroom-spawn",
      "price": 299,
      "compareAtPrice": 349,
      "stock": 50,
      "sku": "SP-OY-1KG",
      "rating": 4.9,
      "reviewCount": 34,
      "shortDescription": "Essential starting material for mushroom cultivation, for growers and enthusiasts.",
      "longDescription": "Mushroom spawn is the essential starting material for mushroom cultivation. Produced by our team with years of hands-on experience in the mushroom industry, this spawn is intended for growers and customers interested in cultivating mushrooms themselves.",
      "ingredients": "Oyster mushroom spawn on sterilised grain.",
      "benefits": [
        "Produced with 15 years of cultivation experience",
        "The essential start material for cultivation",
        "For growers and home cultivators"
      ],
      "usage": "Inoculate your prepared substrate or growing medium as per standard cultivation practice.",
      "shelfLife": "Use within 7 days of delivery. Store in a cool, dry place away from sunlight.",
      "tags": [
        "Bestseller",
        "New"
      ],
      "images": [
        "https://images.unsplash.com/photo-1608686207856-001b95cf60ca?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop"
      ],
      "variants": [
        {
          "name": "500g Bag",
          "price": 179,
          "compareAtPrice": 219,
          "sku": "SP-OY-500",
          "stock": 25
        },
        {
          "name": "1kg Bag",
          "price": 299,
          "compareAtPrice": 349,
          "sku": "SP-OY-1KG",
          "stock": 25
        }
      ],
      "status": "active"
    },
    {
      "id": "prod-104",
      "slug": "button-mushroom-spawn",
      "name": "Button Mushroom Spawn",
      "category": "Mushroom Spawn",
      "categorySlug": "mushroom-spawn",
      "price": 279,
      "compareAtPrice": 329,
      "stock": 45,
      "sku": "SP-BT-1KG",
      "rating": 4.8,
      "reviewCount": 21,
      "shortDescription": "Button mushroom spawn for cultivation — an essential part of our work.",
      "longDescription": "Spawn is an essential starting material for mushroom cultivation, and our experience in the mushroom industry gives this category an important place in our company. Intended for growers and customers interested in mushroom cultivation.",
      "ingredients": "Button mushroom spawn on sterilised grain.",
      "benefits": [
        "Produced with 15 years of cultivation experience",
        "The essential start material for cultivation",
        "For growers and home cultivators"
      ],
      "usage": "Inoculate your prepared substrate or growing medium as per standard cultivation practice.",
      "shelfLife": "Use within 7 days of delivery. Store in a cool, dry place away from sunlight.",
      "tags": [],
      "images": [
        "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1608686207856-001b95cf60ca?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop"
      ],
      "variants": [
        {
          "name": "1kg Bag",
          "price": 279,
          "compareAtPrice": 329,
          "sku": "SP-BT-1KG",
          "stock": 45
        }
      ],
      "status": "active"
    },
    {
      "id": "prod-105",
      "slug": "mushroom-powder",
      "name": "Mushroom Powder",
      "category": "Mushroom Powder",
      "categorySlug": "mushroom-powder",
      "price": 449,
      "compareAtPrice": 549,
      "stock": 45,
      "sku": "MP-100",
      "rating": 4.8,
      "reviewCount": 31,
      "shortDescription": "A convenient way to incorporate mushrooms into everyday foods and recipes.",
      "longDescription": "Mushroom powder is a convenient way to incorporate mushrooms into different foods and recipes. It can be used as an ingredient in cooking and adds mushroom flavour to a variety of dishes — part of our effort to create convenient, versatile mushroom-based products for customers.",
      "ingredients": "100% Dried Mushrooms, ground.",
      "benefits": [
        "100% mushroom-based",
        "Convenient everyday ingredient",
        "Adds mushroom flavour to any dish"
      ],
      "usage": "Add 1 tsp to soups, gravies, dals, smoothies, or doughs while cooking.",
      "shelfLife": "Shelf life as marked on pack. Store in an airtight container.",
      "tags": [
        "Bestseller"
      ],
      "images": [
        "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1514733670139-4d87a1941d55?q=80&w=800&auto=format&fit=crop"
      ],
      "variants": [
        {
          "name": "100g Pouch",
          "price": 449,
          "compareAtPrice": 549,
          "sku": "MP-100",
          "stock": 25
        },
        {
          "name": "250g Pouch",
          "price": 999,
          "compareAtPrice": 1199,
          "sku": "MP-250",
          "stock": 20
        }
      ],
      "status": "active"
    },
    {
      "id": "prod-106",
      "slug": "oyster-mushroom-pickle",
      "name": "Oyster Mushroom Pickle",
      "category": "Mushroom Pickle",
      "categorySlug": "mushroom-pickle",
      "price": 349,
      "compareAtPrice": 425,
      "stock": 60,
      "sku": "PK-OY-250",
      "rating": 4.9,
      "reviewCount": 44,
      "shortDescription": "Mushrooms in a traditional and flavourful pickle form.",
      "longDescription": "Mushroom pickle brings mushrooms into a traditional and flavourful form — a different way to enjoy mushrooms as part of your meals. One of our value-added mushroom products, created to offer something different from fresh mushrooms.",
      "ingredients": "Fresh Oyster Mushrooms, Mustard Oil, Spices & Salt.",
      "benefits": [
        "Traditional flavourful format",
        "A value-added mushroom product",
        "Great with rice and Indian bread"
      ],
      "usage": "Serve alongside hot rice, parathas, or any meal of your choice.",
      "shelfLife": "Shelf life as marked on pack. Store in a cool, dry place.",
      "tags": [
        "Bestseller"
      ],
      "images": [
        "https://images.unsplash.com/photo-1534483509719-3feaee7c30da?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?q=80&w=800&auto=format&fit=crop"
      ],
      "variants": [
        {
          "name": "250g Jar",
          "price": 349,
          "compareAtPrice": 425,
          "sku": "PK-OY-250",
          "stock": 35
        },
        {
          "name": "500g Jar",
          "price": 629,
          "compareAtPrice": 749,
          "sku": "PK-OY-500",
          "stock": 25
        }
      ],
      "status": "active"
    },
    {
      "id": "prod-107",
      "slug": "button-mushroom-pickle",
      "name": "Button Mushroom Pickle",
      "category": "Mushroom Pickle",
      "categorySlug": "mushroom-pickle",
      "price": 329,
      "compareAtPrice": 399,
      "stock": 40,
      "sku": "PK-BT-250",
      "rating": 4.7,
      "reviewCount": 27,
      "shortDescription": "A value-added mushroom product in a familiar, flavourful form.",
      "longDescription": "A flavourful mushroom pickle made from fresh button mushrooms — part of our range of value-added mushroom products. It offers customers a different way to enjoy mushrooms alongside their everyday meals.",
      "ingredients": "Fresh Button Mushrooms, Mustard Oil, Spices & Salt.",
      "benefits": [
        "Traditional flavourful format",
        "A value-added mushroom product",
        "Made from fresh farm mushrooms"
      ],
      "usage": "Serve alongside hot rice, parathas, or any meal of your choice.",
      "shelfLife": "Shelf life as marked on pack. Store in a cool, dry place.",
      "tags": [],
      "images": [
        "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1534483509719-3feaee7c30da?q=80&w=800&auto=format&fit=crop"
      ],
      "variants": [
        {
          "name": "250g Jar",
          "price": 329,
          "compareAtPrice": 399,
          "sku": "PK-BT-250",
          "stock": 25
        },
        {
          "name": "500g Jar",
          "price": 599,
          "compareAtPrice": 699,
          "sku": "PK-BT-500",
          "stock": 15
        }
      ],
      "status": "active"
    },
    {
      "id": "prod-108",
      "slug": "sun-dried-oyster-mushrooms",
      "name": "Sun-Dried Oyster Mushrooms",
      "category": "Sun-Dried Mushrooms",
      "categorySlug": "sun-dried-mushrooms",
      "price": 399,
      "compareAtPrice": 479,
      "stock": 40,
      "sku": "SD-OY-100",
      "rating": 4.8,
      "reviewCount": 29,
      "shortDescription": "Dried oyster mushrooms for storage and use across many types of cooking.",
      "longDescription": "Our sun-dried mushroom products provide another way to enjoy mushrooms beyond their fresh form. Drying allows mushrooms to be stored and used across different types of cooking — a convenient mushroom option for any kitchen.",
      "ingredients": "100% Sun-Dried Oyster Mushrooms.",
      "benefits": [
        "Store and use across many types of cooking",
        "Concentrated mushroom flavour",
        "A convenient pantry staple"
      ],
      "usage": "Rehydrate in warm water for 10–15 minutes before adding to curries, stir-fries, and soups.",
      "shelfLife": "Shelf life as marked on pack. Store in an airtight container.",
      "tags": [
        "New"
      ],
      "images": [
        "https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop"
      ],
      "variants": [
        {
          "name": "100g Pouch",
          "price": 399,
          "compareAtPrice": 479,
          "sku": "SD-OY-100",
          "stock": 25
        },
        {
          "name": "250g Pouch",
          "price": 849,
          "compareAtPrice": 999,
          "sku": "SD-OY-250",
          "stock": 15
        }
      ],
      "status": "active"
    },
    {
      "id": "prod-109",
      "slug": "sun-dried-shiitake-mushrooms",
      "name": "Sun-Dried Shiitake Mushrooms",
      "category": "Sun-Dried Mushrooms",
      "categorySlug": "sun-dried-mushrooms",
      "price": 499,
      "compareAtPrice": 599,
      "stock": 35,
      "sku": "SD-SH-100",
      "rating": 4.9,
      "reviewCount": 36,
      "shortDescription": "Dried shiitake mushrooms that store well and cook beautifully.",
      "longDescription": "Sun-dried shiitake mushrooms — another convenient way to enjoy mushrooms beyond their fresh form. Drying allows them to be stored and used in different types of cooking, from rice dishes to gravies and soups.",
      "ingredients": "100% Sun-Dried Shiitake Mushrooms.",
      "benefits": [
        "Store and use across many types of cooking",
        "Concentrated mushroom flavour",
        "A convenient pantry staple"
      ],
      "usage": "Rehydrate in warm water for 15–20 minutes before adding to your cooking. Use the soaking liquid as stock.",
      "shelfLife": "Shelf life as marked on pack. Store in an airtight container.",
      "tags": [
        "Bestseller"
      ],
      "images": [
        "https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=800&auto=format&fit=crop"
      ],
      "variants": [
        {
          "name": "100g Pouch",
          "price": 499,
          "compareAtPrice": 599,
          "sku": "SD-SH-100",
          "stock": 25
        },
        {
          "name": "250g Pouch",
          "price": 1099,
          "compareAtPrice": 1299,
          "sku": "SD-SH-250",
          "stock": 10
        }
      ],
      "status": "active"
    },
    {
      "id": "prod-110",
      "slug": "mushroom-soup-mix",
      "name": "Mushroom Soup Mix",
      "category": "Mushroom Soup Mix",
      "categorySlug": "mushroom-soup-mix",
      "price": 349,
      "compareAtPrice": 429,
      "stock": 45,
      "sku": "SP-200",
      "rating": 4.7,
      "reviewCount": 24,
      "shortDescription": "A convenient way to prepare mushroom soup at home.",
      "longDescription": "Our mushroom soup mix is designed for customers looking for a convenient mushroom-based food option. It provides an easy way to prepare mushroom soup while bringing the flavour of mushrooms into a simple, convenient product.",
      "ingredients": "Dried Mushroom Powder, Spices & Seasoning.",
      "benefits": [
        "Easy way to prepare mushroom soup",
        "A convenient everyday option",
        "Brings mushroom flavour to a simple meal"
      ],
      "usage": "Stir into hot water or milk, simmer for a few minutes while stirring, and serve hot.",
      "shelfLife": "Shelf life as marked on pack. Store in an airtight container.",
      "tags": [],
      "images": [
        "https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1547592180-85f173990554?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=800&auto=format&fit=crop"
      ],
      "variants": [
        {
          "name": "200g Pouch",
          "price": 349,
          "compareAtPrice": 429,
          "sku": "SP-200",
          "stock": 30
        },
        {
          "name": "500g Pouch",
          "price": 749,
          "compareAtPrice": 899,
          "sku": "SP-500",
          "stock": 15
        }
      ],
      "status": "active"
    },
    {
      "id": "prod-111",
      "slug": "mushroom-chutney",
      "name": "Mushroom Chutney",
      "category": "Mushroom Chutney",
      "categorySlug": "mushroom-chutney",
      "price": 299,
      "compareAtPrice": 349,
      "stock": 55,
      "sku": "CH-220",
      "rating": 4.8,
      "reviewCount": 38,
      "shortDescription": "A familiar and enjoyable food format for mushroom lovers.",
      "longDescription": "Mushroom chutney is another value-added product in our range. It combines the versatility of mushrooms with a familiar and enjoyable food format — served as an accompaniment with meals, it gives customers another way to enjoy mushroom-based food.",
      "ingredients": "Mushrooms, Spices, Oil & Salt.",
      "benefits": [
        "Familiar, enjoyable accompaniment",
        "A value-added mushroom product",
        "Serves with meals of all kinds"
      ],
      "usage": "Serve as an accompaniment with rice, roti, dosa, sandwiches, or snacks.",
      "shelfLife": "Shelf life as marked on pack. Store in a cool, dry place.",
      "tags": [
        "Bestseller"
      ],
      "images": [
        "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1534483509719-3feaee7c30da?q=80&w=800&auto=format&fit=crop"
      ],
      "variants": [
        {
          "name": "220g Jar",
          "price": 299,
          "compareAtPrice": 349,
          "sku": "CH-220",
          "stock": 35
        },
        {
          "name": "450g Jar",
          "price": 549,
          "compareAtPrice": 649,
          "sku": "CH-450",
          "stock": 20
        }
      ],
      "status": "active"
    },
    {
      "id": "prod-112",
      "slug": "oyster-home-growing-kit",
      "name": "Oyster Mushroom Home Growing Kit",
      "category": "Home Growing Kit",
      "categorySlug": "home-growing-kit",
      "price": 699,
      "compareAtPrice": 899,
      "stock": 20,
      "sku": "GK-OY-01",
      "rating": 4.9,
      "reviewCount": 52,
      "shortDescription": "An accessible way to experience mushroom cultivation at home.",
      "longDescription": "For people interested in experiencing mushroom cultivation themselves, our Home Growing Kit provides an accessible way to explore growing mushrooms at home. Mushroom cultivation should not only be something people see on a farm — it can also be an interesting experience for anyone who wants to understand how mushrooms grow and enjoy the process themselves.",
      "ingredients": "Pre-spawned growing block, misting bottle & instruction booklet.",
      "benefits": [
        "Experience cultivation at your home",
        "Understand how mushrooms grow",
        "Accessible for beginners"
      ],
      "usage": "Open the kit as directed, mist with clean water, and watch your fresh mushrooms grow.",
      "shelfLife": "Use within 60 days of delivery",
      "tags": [
        "Bestseller"
      ],
      "images": [
        "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?q=80&w=800&auto=format&fit=crop"
      ],
      "variants": [
        {
          "name": "Single Grow Kit",
          "price": 699,
          "compareAtPrice": 899,
          "sku": "GK-OY-01",
          "stock": 12
        },
        {
          "name": "Duo Grow Kit",
          "price": 1299,
          "compareAtPrice": 1599,
          "sku": "GK-OY-02",
          "stock": 8
        }
      ],
      "status": "active"
    },
    {
      "id": "prod-113",
      "slug": "farm-combo-pack",
      "name": "Farm Combo Pack",
      "category": "Farm Combo Pack",
      "categorySlug": "farm-combo-pack",
      "price": 999,
      "compareAtPrice": 1199,
      "stock": 25,
      "sku": "CB-FM-01",
      "rating": 4.9,
      "reviewCount": 22,
      "shortDescription": "Selected mushroom products together in one convenient package.",
      "longDescription": "Our Farm Combo Pack brings selected mushroom products together in one convenient package. It is designed for customers who want to explore more than one product from our range — a convenient way to experience different products from our mushroom business.",
      "ingredients": "Assorted mushroom products from our range. See pack for contents.",
      "benefits": [
        "Explore more than one product",
        "Selected products in one package",
        "A convenient way to try our range"
      ],
      "usage": "Gift it or enjoy across daily meals — from breakfast to dinner.",
      "shelfLife": "Shelf life as marked on pack",
      "tags": [
        "Bestseller"
      ],
      "images": [
        "https://images.unsplash.com/photo-1608686207856-001b95cf60ca?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1534483509719-3feaee7c30da?q=80&w=800&auto=format&fit=crop"
      ],
      "variants": [
        {
          "name": "Combo Pack",
          "price": 999,
          "compareAtPrice": 1199,
          "sku": "CB-FM-01",
          "stock": 25
        }
      ],
      "status": "active"
    }
  ],
  "categories": [
    {
      "id": "cat-1",
      "name": "Fresh Mushrooms",
      "slug": "fresh-mushrooms",
      "description": "Fresh mushrooms for everyday cooking and food preparation.",
      "image": "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop",
      "featured": true,
      "itemCount": 2
    },
    {
      "id": "cat-2",
      "name": "Mushroom Spawn",
      "slug": "mushroom-spawn",
      "description": "The essential starting material for mushroom cultivation.",
      "image": "https://images.unsplash.com/photo-1608686207856-001b95cf60ca?q=80&w=800&auto=format&fit=crop",
      "featured": true,
      "itemCount": 2
    },
    {
      "id": "cat-3",
      "name": "Mushroom Powder",
      "slug": "mushroom-powder",
      "description": "A convenient way to add mushroom flavour to cooking and recipes.",
      "image": "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?q=80&w=800&auto=format&fit=crop",
      "featured": true,
      "itemCount": 1
    },
    {
      "id": "cat-4",
      "name": "Mushroom Pickle",
      "slug": "mushroom-pickle",
      "description": "A traditional, flavourful form — a value-added mushroom product.",
      "image": "https://images.unsplash.com/photo-1534483509719-3feaee7c30da?q=80&w=800&auto=format&fit=crop",
      "featured": true,
      "itemCount": 2
    },
    {
      "id": "cat-5",
      "name": "Sun-Dried Mushrooms",
      "slug": "sun-dried-mushrooms",
      "description": "Dried for storage and use across many types of cooking.",
      "image": "https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?q=80&w=800&auto=format&fit=crop",
      "featured": true,
      "itemCount": 2
    },
    {
      "id": "cat-6",
      "name": "Mushroom Soup Mix",
      "slug": "mushroom-soup-mix",
      "description": "An easy way to prepare mushroom soup at home.",
      "image": "https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800&auto=format&fit=crop",
      "featured": false,
      "itemCount": 1
    },
    {
      "id": "cat-7",
      "name": "Mushroom Chutney",
      "slug": "mushroom-chutney",
      "description": "A familiar accompaniment that combines mushrooms with an everyday format.",
      "image": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=800&auto=format&fit=crop",
      "featured": false,
      "itemCount": 1
    },
    {
      "id": "cat-8",
      "name": "Home Growing Kit",
      "slug": "home-growing-kit",
      "description": "An accessible way to experience mushroom cultivation at home.",
      "image": "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop",
      "featured": true,
      "itemCount": 1
    },
    {
      "id": "cat-9",
      "name": "Farm Combo Pack",
      "slug": "farm-combo-pack",
      "description": "Selected mushroom products together in one convenient package.",
      "image": "https://images.unsplash.com/photo-1608686207856-001b95cf60ca?q=80&w=800&auto=format&fit=crop",
      "featured": true,
      "itemCount": 1
    }
  ],
  "coupons": [
    {
      "id": "coup-1",
      "code": "WELCOME10",
      "discountType": "percentage",
      "discountValue": 10,
      "minOrderAmount": 499,
      "maxDiscount": 200,
      "expiryDate": "2026-12-31",
      "usageLimit": 1000,
      "usedCount": 142,
      "active": true,
      "description": "10% Off on your first order over ₹499"
    },
    {
      "id": "coup-2",
      "code": "FUNGI15",
      "discountType": "percentage",
      "discountValue": 15,
      "minOrderAmount": 1499,
      "maxDiscount": 500,
      "expiryDate": "2026-11-30",
      "usageLimit": 500,
      "usedCount": 89,
      "active": true,
      "description": "15% Off on premium harvests over ₹1499"
    },
    {
      "id": "coup-3",
      "code": "FARMFLAT200",
      "discountType": "flat",
      "discountValue": 200,
      "minOrderAmount": 1999,
      "maxDiscount": 200,
      "expiryDate": "2026-10-31",
      "usageLimit": 250,
      "usedCount": 45,
      "active": true,
      "description": "Flat ₹200 discount on combo packs & bulk orders"
    }
  ],
  "reviews": [
    {
      "id": "rev-1",
      "productId": "prod-101",
      "productName": "Fresh Oyster Mushrooms",
      "author": "Ananya Iyer",
      "rating": 5,
      "date": "2026-09-15",
      "verifiedPurchase": true,
      "status": "approved",
      "title": "Fresh and carefully packed",
      "content": "The oyster mushrooms arrived clean and fresh. Cooked beautifully in a simple stir-fry. You can tell they are handled with care."
    },
    {
      "id": "rev-2",
      "productId": "prod-106",
      "productName": "Oyster Mushroom Pickle",
      "author": "Rajesh K.",
      "rating": 5,
      "date": "2026-09-20",
      "verifiedPurchase": true,
      "status": "approved",
      "title": "A different way to enjoy mushrooms",
      "content": "Traditional flavour, not too heavy, and the mushroom pieces stay firm. Goes very well with hot rice. Ordering again."
    },
    {
      "id": "rev-3",
      "productId": "prod-112",
      "productName": "Oyster Mushroom Home Growing Kit",
      "author": "Meera Nair",
      "rating": 5,
      "date": "2026-09-22",
      "verifiedPurchase": true,
      "status": "approved",
      "title": "Fascinating to watch mushrooms grow",
      "content": "The kit was easy to follow and it was genuinely interesting to see the full growing process at home. Great experience for the family."
    },
    {
      "id": "rev-4",
      "productId": "prod-109",
      "productName": "Sun-Dried Shiitake Mushrooms",
      "author": "Chef Devendra P.",
      "rating": 4,
      "date": "2026-09-25",
      "verifiedPurchase": true,
      "status": "approved",
      "title": "Convenient pantry staple",
      "content": "Rehydrated well and the flavour was deep and mushroomy. The soaking liquid made a lovely base for stock. Good quality dried mushrooms."
    }
  ],
  "blogs": [
    {
      "id": "blog-1",
      "slug": "15-years-of-experience-one-passion",
      "title": "15 Years of Experience. One Passion.",
      "excerpt": "The story of MANASI MUSHROOM & SPAWN PVT. LTD. — how Mrs. Manasi Pattanayak''s hands-on work in mushroom cultivation became a growing company.",
      "category": "Our Journey",
      "author": "Team MANASI",
      "date": "Sep 18, 2026",
      "readTime": "5 min read",
      "image": "https://images.unsplash.com/photo-1547592180-85f173990554?q=80&w=800&auto=format&fit=crop",
      "featured": true,
      "content": "\n      <p>The story of MANASI MUSHROOM &amp; SPAWN PVT. LTD. began with Mrs. Manasi Pattanayak, the founder behind our journey. With 15 years of experience in mushroom cultivation and the mushroom industry, she has developed valuable practical knowledge through years of working directly with mushrooms — cultivation, production, handling, and mushroom-based products.</p>\n      <h3>From Cultivation to a Structured Business</h3>\n      <p>What started as a journey in mushroom cultivation gradually developed into a larger vision. Years of experience, learning, experimentation, and dedication created the foundation for building a professionally structured mushroom business.</p>\n      <h3>A New Chapter in 2026</h3>\n      <p>In 2026, this journey took an important step forward when the business was officially registered as MANASI MUSHROOM &amp; SPAWN PVT. LTD. This new chapter represents the combination of years of practical experience with a growing vision for the future — serving customers across India with trust.</p>\n    "
    },
    {
      "id": "blog-2",
      "slug": "how-our-farm-works",
      "title": "From Our Farm: How Cultivation, Care & Products Come Together",
      "excerpt": "A look at our farm in Pedagadi, Udala, Mayurbhanj, Odisha — where every cultivation cycle begins with attention and proper care.",
      "category": "Farm & Field",
      "author": "Team MANASI",
      "date": "Sep 10, 2026",
      "readTime": "6 min read",
      "image": "https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=800&auto=format&fit=crop",
      "featured": true,
      "content": "\n      <p>Our farm is the heart of MANASI MUSHROOM &amp; SPAWN PVT. LTD. Located in Pedagadi, Udala, Mayurbhanj, Odisha, it is where our journey with mushrooms comes to life and where every cultivation cycle requires attention and proper care.</p>\n      <h3>Care at Every Stage</h3>\n      <p>Every cycle follows the same disciplined path: preparing the growing environment, monitoring mushroom growth, and carefully handling the final produce. Good products begin with proper cultivation and careful handling at the farm level.</p>\n      <h3>From Farm to Products</h3>\n      <p>From cultivation to processing, our farm is the starting point of many of our mushroom products. Fresh mushrooms, mushroom spawn, and other mushroom-based products are all connected to the knowledge and experience developed through our work in cultivation.</p>\n    "
    },
    {
      "id": "blog-3",
      "slug": "mushrooms-in-everyday-cooking",
      "title": "Mushrooms in Everyday Cooking: Powder, Pickle, Soup Mix & More",
      "excerpt": "Different ways to enjoy mushrooms at home — from fresh cooking to convenient mushroom-based products for everyday use.",
      "category": "Kitchen Notes",
      "author": "Team MANASI",
      "date": "Aug 28, 2026",
      "readTime": "4 min read",
      "image": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800&auto=format&fit=crop",
      "featured": false,
      "content": "\n      <p>Mushrooms are a versatile ingredient for homes, restaurants, and food businesses. Our product range is designed to provide different ways to enjoy and explore mushrooms in everyday cooking.</p>\n      <h3>Many Forms, One Ingredient</h3>\n      <p>Fresh mushrooms can be used in a wide variety of dishes. Sun-dried mushrooms can be stored and used across different types of cooking, while mushroom powder adds mushroom flavour to soups, gravies, and doughs with a simple spoonful.</p>\n      <h3>Convenient, Value-Added Products</h3>\n      <p>Mushroom pickle and mushroom chutney bring mushrooms into familiar, flavourful formats to serve alongside meals. Our mushroom soup mix offers an easy way to prepare mushroom soup at home — convenient food options that bring the flavour of mushrooms to the table.</p>\n    "
    }
  ],
  "banners": [
    {
      "id": "ban-1",
      "title": "Fresh Mushrooms. Healthy Life.",
      "subtitle": "Cultivated, processed & packed by MANASI MUSHROOM & SPAWN PVT. LTD.",
      "ctaText": "Explore Collection",
      "ctaLink": "/shop",
      "image": "https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=1200&auto=format&fit=crop",
      "active": true,
      "position": "hero-1"
    },
    {
      "id": "ban-2",
      "title": "Supplying Across India With Trust.",
      "subtitle": "From our farm in Odisha — guaranteed freshness & quality.",
      "ctaText": "Our Farm",
      "ctaLink": "/our-farm",
      "image": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1200&auto=format&fit=crop",
      "active": true,
      "position": "hero-2"
    },
    {
      "id": "ban-3",
      "title": "Grow Mushrooms At Home",
      "subtitle": "Home growing kits & mushroom spawn for every kind of grower",
      "ctaText": "Shop Growing Supplies",
      "ctaLink": "/category/home-growing-kit",
      "image": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?q=80&w=1200&auto=format&fit=crop",
      "active": true,
      "position": "promo-banner"
    }
  ],
  "faqs": [
    {
      "id": "faq-1",
      "question": "Who is MANASI MUSHROOM & SPAWN PVT. LTD.?",
      "answer": "We are a mushroom-focused company built on experience, dedication, quality, and a strong connection with mushroom cultivation. Founded by Mrs. Manasi Pattanayak, who has 15 years of experience in mushroom cultivation and the mushroom industry, the company was officially registered in 2026. Our roots are in Pedagadi, Udala, Mayurbhanj, Odisha."
    },
    {
      "id": "faq-2",
      "question": "What products do you offer?",
      "answer": "Our work covers mushroom cultivation, mushroom spawn production, and mushroom-based food products. Our range includes fresh mushrooms, mushroom spawn, sun-dried mushrooms, mushroom powder, mushroom pickle, mushroom soup mix, mushroom chutney, a home growing kit, and a farm combo pack."
    },
    {
      "id": "faq-3",
      "question": "Where is your farm located?",
      "answer": "Our farm is located in Pedagadi, Udala, Mayurbhanj, Odisha. It is the heart of our company and the starting point of many of our mushroom products — from fresh mushrooms and spawn to processed products."
    },
    {
      "id": "faq-4",
      "question": "Do you ship across India?",
      "answer": "Yes — our brand line is ''Supplying Across India With Trust.'' We work toward serving customers from different parts of India. Orders over ₹999 qualify for complimentary shipping on this store."
    },
    {
      "id": "faq-5",
      "question": "Do you sell spawn and home growing kits?",
      "answer": "Yes. Mushroom spawn is an essential starting material for mushroom cultivation and is intended for growers and customers interested in cultivation. Our Home Growing Kit offers an accessible way to experience growing mushrooms at home."
    }
  ],
  "customers": [
    {
      "id": "cust-1",
      "name": "Aarav Sharma",
      "email": "aarav.sharma@example.com",
      "phone": "+91 98123 45678",
      "ordersCount": 4,
      "totalSpent": 7850,
      "status": "active",
      "joinDate": "2026-03-12",
      "addresses": [
        {
          "id": "addr-1",
          "label": "Home",
          "name": "Aarav Sharma",
          "phone": "+91 98123 45678",
          "street": "42 Golf Links, Apartment 3B",
          "city": "New Delhi",
          "state": "Delhi",
          "pincode": "110003",
          "isDefault": true
        }
      ]
    },
    {
      "id": "cust-2",
      "name": "Priyanjali Sen",
      "email": "priya.sen@example.com",
      "phone": "+91 97654 32109",
      "ordersCount": 2,
      "totalSpent": 3120,
      "status": "active",
      "joinDate": "2026-05-20",
      "addresses": [
        {
          "id": "addr-2",
          "label": "Office",
          "name": "Priyanjali Sen",
          "phone": "+91 97654 32109",
          "street": "18 Jubilee Hills, Road No 10",
          "city": "Hyderabad",
          "state": "Telangana",
          "pincode": "500033",
          "isDefault": true
        }
      ]
    },
    {
      "id": "cust-3",
      "name": "Vikramaditya Roy",
      "email": "vikram.roy@example.com",
      "phone": "+91 99887 76655",
      "ordersCount": 1,
      "totalSpent": 3306,
      "status": "active",
      "joinDate": "2026-09-01",
      "addresses": [
        {
          "id": "addr-3",
          "label": "Home",
          "name": "Vikramaditya Roy",
          "phone": "+91 99887 76655",
          "street": "75 Koregaon Park, Lane 4",
          "city": "Pune",
          "state": "Maharashtra",
          "pincode": "411001",
          "isDefault": true
        }
      ]
    }
  ],
  "messages": [
    {
      "id": "msg-1",
      "name": "Devika Malhotra",
      "email": "devika@example.com",
      "phone": "+91 98765 11223",
      "subject": "Bulk Mushroom Powder & Spawn Inquiry",
      "message": "Hello, we operate a restaurant chain in Bengaluru and would like to enquire about wholesale pricing for mushroom powder and fresh mushrooms, plus spawn for our own growing unit.",
      "date": "2026-09-29T16:20:00.000Z",
      "read": false
    }
  ],
  "subscribers": [
    {
      "id": "sub-1",
      "email": "gourmet.lover@example.com",
      "date": "2026-09-15"
    },
    {
      "id": "sub-2",
      "email": "culinary.chef@example.com",
      "date": "2026-09-22"
    }
  ],
  "orders": [
    {
      "id": "ORD-89241",
      "date": "2026-09-28T14:32:00.000Z",
      "customer": {
        "name": "Aarav Sharma",
        "email": "aarav.sharma@example.com",
        "phone": "+91 98123 45678",
        "address": "42 Golf Links, Apartment 3B",
        "city": "New Delhi",
        "state": "Delhi",
        "pincode": "110003"
      },
      "items": [
        {
          "id": "prod-105",
          "name": "Mushroom Powder",
          "variant": "100g Pouch",
          "price": 449,
          "quantity": 2,
          "image": "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?q=80&w=800&auto=format&fit=crop"
        },
        {
          "id": "prod-106",
          "name": "Oyster Mushroom Pickle",
          "variant": "250g Jar",
          "price": 349,
          "quantity": 1,
          "image": "https://images.unsplash.com/photo-1534483509719-3feaee7c30da?q=80&w=800&auto=format&fit=crop"
        }
      ],
      "subtotal": 1247,
      "discount": 100,
      "couponCode": "WELCOME10",
      "tax": 57,
      "shippingFee": 0,
      "total": 1204,
      "status": "Delivered",
      "paymentMethod": "UPI",
      "paymentStatus": "Paid",
      "trackingNumber": "TRK-IN-9920148",
      "timeline": [
        {
          "status": "Placed",
          "time": "Sep 28, 02:32 PM",
          "done": true
        },
        {
          "status": "Confirmed",
          "time": "Sep 28, 03:00 PM",
          "done": true
        },
        {
          "status": "Packed",
          "time": "Sep 29, 09:15 AM",
          "done": true
        },
        {
          "status": "Shipped",
          "time": "Sep 29, 02:30 PM",
          "done": true
        },
        {
          "status": "Delivered",
          "time": "Oct 01, 11:20 AM",
          "done": true
        }
      ]
    },
    {
      "id": "ORD-89242",
      "date": "2026-09-30T10:15:00.000Z",
      "customer": {
        "name": "Priyanjali Sen",
        "email": "priya.sen@example.com",
        "phone": "+91 97654 32109",
        "address": "18 Jubilee Hills, Road No 10",
        "city": "Hyderabad",
        "state": "Telangana",
        "pincode": "500033"
      },
      "items": [
        {
          "id": "prod-112",
          "name": "Oyster Mushroom Home Growing Kit",
          "variant": "Single Grow Kit",
          "price": 699,
          "quantity": 1,
          "image": "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop"
        }
      ],
      "subtotal": 699,
      "discount": 0,
      "couponCode": "",
      "tax": 35,
      "shippingFee": 99,
      "total": 833,
      "status": "Shipped",
      "paymentMethod": "Credit Card",
      "paymentStatus": "Paid",
      "trackingNumber": "TRK-IN-9920311",
      "timeline": [
        {
          "status": "Placed",
          "time": "Sep 30, 10:15 AM",
          "done": true
        },
        {
          "status": "Confirmed",
          "time": "Sep 30, 10:30 AM",
          "done": true
        },
        {
          "status": "Packed",
          "time": "Sep 30, 04:00 PM",
          "done": true
        },
        {
          "status": "Shipped",
          "time": "Oct 01, 09:00 AM",
          "done": true
        },
        {
          "status": "Delivered",
          "time": "Expected Oct 03",
          "done": false
        }
      ]
    },
    {
      "id": "ORD-89243",
      "date": "2026-10-01T08:45:00.000Z",
      "customer": {
        "name": "Vikramaditya Roy",
        "email": "vikram.roy@example.com",
        "phone": "+91 99887 76655",
        "address": "75 Koregaon Park, Lane 4",
        "city": "Pune",
        "state": "Maharashtra",
        "pincode": "411001"
      },
      "items": [
        {
          "id": "prod-109",
          "name": "Sun-Dried Shiitake Mushrooms",
          "variant": "100g Pouch",
          "price": 499,
          "quantity": 1,
          "image": "https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?q=80&w=800&auto=format&fit=crop"
        }
      ],
      "subtotal": 499,
      "discount": 0,
      "couponCode": "",
      "tax": 25,
      "shippingFee": 99,
      "total": 623,
      "status": "Confirmed",
      "paymentMethod": "Cash on Delivery",
      "paymentStatus": "Pending",
      "trackingNumber": "TRK-IN-9920405",
      "timeline": [
        {
          "status": "Placed",
          "time": "Oct 01, 08:45 AM",
          "done": true
        },
        {
          "status": "Confirmed",
          "time": "Oct 01, 09:15 AM",
          "done": true
        },
        {
          "status": "Packed",
          "time": "Pending",
          "done": false
        },
        {
          "status": "Shipped",
          "time": "Pending",
          "done": false
        },
        {
          "status": "Delivered",
          "time": "Pending",
          "done": false
        }
      ]
    }
  ],
  "settings": {
    "site_config": {
      "name": "MANASI MUSHROOM",
      "tagline": "15 Years of Experience. One Passion.",
      "logoText": "MANASI",
      "subtitle": "Supplying Across India with Trust",
      "currencySymbol": "₹",
      "currencyCode": "INR",
      "gstPercentage": 5,
      "freeShippingThreshold": 999,
      "defaultShippingFee": 99,
      "phone": "+91 98765 43210",
      "whatsapp": "+919876543210",
      "email": "concierge@brandname.com",
      "address": "Pedagadi, Udala, Mayurbhanj, Odisha, India",
      "hours": "Mon - Sat: 9:00 AM - 7:00 PM IST",
      "socials": {
        "instagram": "https://instagram.com/brandname",
        "facebook": "https://facebook.com/brandname",
        "pinterest": "https://pinterest.com/brandname",
        "youtube": "https://youtube.com/brandname"
      },
      "announcementText": "Complimentary Express Shipping on orders over ₹999 | Handcrafted Harvest",
      "aboutShort": "MANASI MUSHROOM & SPAWN PVT. LTD. is a mushroom-focused company built on experience, dedication, quality, and a strong connection with mushroom cultivation — rooted in Pedagadi, Udala, Mayurbhanj, Odisha, and serving customers across India.",
      "farmStory": "Our journey began with 15 years of hands-on mushroom cultivation. From our farm in Odisha, every cycle is guided by attention and proper care — from preparing the growing environment to handling the final produce."
    },
    "shipping_tax": {
      "gstPercentage": 5,
      "freeShippingThreshold": 999,
      "flatShippingFee": 99,
      "pincodes": [
        "110001",
        "110003",
        "411001",
        "500033",
        "400001",
        "560001",
        "600001",
        "700001",
        "173212"
      ]
    }
  }
}'::jsonb)
on conflict (key) do update set data = excluded.data;
